[project]
name = "financial-document-analyzer-debug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai[tools]>=0.165.1",
    "fastapi>=0.116.1",
    "python-multipart>=0.0.20",
]
